name: Build Workflow
on:
  push:
    branches:
      - main
      - github_actions
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download Node
        uses: actions/setup-node@v1
      - name: Check Node/NPM Version
        run: |
          node -v
          npm -v
      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-assets
          path: static

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Assets
        uses: actions/download-artifact@v2
        with:
          name: build-assets

