name: Test Workflow
on:
  push:
    branches:
      - main
      - github_actions
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download Node
        uses: actions/setup-node@v1
      - name: Check Node Version
        run: node -v
      - name: Check NPM Version
        run: npm -v

